### ISSUE TITLE
UnicodeDecodeError due to truncated data when running autoruns

### ISSUE THREAD

**Issue by JesseBowling** [tomchop/volatility-autoruns#13]
Getting a Unicode error on this image; stack trace below. Results in no output given. Can this error be caught so some output is given?

Volatility Foundation Volatility Framework 2.5

Traceback (most recent call last):
  File "/usr/local/bin/vol.py", line 5, in <module>
    pkg_resources.run_script('volatility==2.5', 'vol.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.5-py2.7.egg/EGG-INFO/scripts/vol.py", line 192, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.5-py2.7.egg/EGG-INFO/scripts/vol.py", line 183, in main
    command.execute()
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.5-py2.7.egg/volatility/commands.py", line 119, in execute
    data = self.calculate()
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.5-py2.7.egg/volatility/plugins/autoruns.py", line 531, in calculate
    self.tasks = self.get_tasks()
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.5-py2.7.egg/volatility/plugins/autoruns.py", line 450, in get_tasks
    parsed = self.parse_task_xml(task_xml)
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.5-py2.7.egg/volatility/plugins/autoruns.py", line 466, in parse_task_xml
    xml = xml.decode('utf-16')
  File "/usr/lib/python2.7/encodings/utf_16.py", line 16, in decode
    return codecs.utf_16_decode(input, errors, True)
UnicodeDecodeError: 'utf16' codec can't decode byte 0x00 in position 0: truncated data

**Comment by tomchop** [comment]
It seems it's having a hard time reading the task XML. Can you do a `print repr(xml)` just before `xml = xml.decode('utf-16')` and tell me what the results are?

**Comment by JesseBowling** [comment]
Comes back as empty...

Here's what I did (which does allow it to complete otherwise unaffected it would seem):

    def parse_task_xml(self, xml):
        raw = xml
        xml = re.sub('\x00\x00+', '', xml) + '\x00'
        try:
            xml = xml.decode('utf-16')
            xml = re.sub(r"<Task(.*?)>", "<Task>", xml)
            xml = xml.encode('utf-16')

            root = ET.fromstring(xml)
            d = {}

            for e in root.findall("./RegistrationInfo/Date"):
                d['Date'] = e.text
            for e in root.findall("./RegistrationInfo/Description"):
                d['Description'] = e.text
            for e in root.findall("./Actions"):
                d['Actions'] = self.visit_all_children(e)
            for e in root.findall("./Settings/Enabled"):
                d['Enabled'] = e.text
            for e in root.findall("./Settings/Hidden"):
                d['Hidden'] = e.text
            for t in root.findall("./Triggers/*"):
                d['Triggers'] = self.visit_all_children(t)

            if not d.get("Actions", {}).get('Exec', {}).get("Command", False):
                return None

            return d
        except UnicodeDecodeError as e:
            sys.stderr.write('UnicodeDecodeError for: {}\n'.format(repr(raw)))

**Comment by jared703** [comment]
Tom,

The GrrCon2012 challenge is giving me what appears to be some unicode errors. I've put a copy of it up here if you want to download and try it on your end.

https://drive.google.com/file/d/0B_OPOV8sZBaYMjYwUTNRaGZYY1k/view?usp=sharing

**Comment by tomchop** [comment]
@jared703: thanks for the heads-up, I'll look into it.

**Comment by tomchop** [comment]
Hm, so I'm not getting unicode errors. Just seeing the service below which has two non-ASCII characters at the end of the name:

```
Services =========================================

Service: DcomLaunch (ntstobject.dll.123.Manifestp) - Share_Process, Auto Start
    Image path: Adobe\Reader\9.3\ARM\AdbeRdr950_en_US.exeȞఎ (Last modified: 2012-04-28 01:56:26 UTC+0000)
    PIDs: -
```

That said, there were some keys that were not properly parsed (missing values), so I fixed that. Care to give it another try and letting me know if you still get an error?

**Comment by jared703** [comment]
Sorry meant to write back - it has been working wonderfully across memory samples with this same issue. Thanks again for the awesome work.

**Comment by tomchop** [comment]
Happy to help. Thanks for testing it so thouroughly ;)
