### ISSUE TITLE
autoruns.py not working

### ISSUE THREAD

**Issue by Arvandor** [tomchop/volatility-autoruns#4]
I put autoruns in the contrib/plugins directory (where I have other working plugins, such as mimikatz,) but when I try to run autoruns, I get the following output

Volatility Foundation Volatility Framework 2.4
Traceback (most recent call last):
  File "/usr/share/volatility/vol.py", line 192, in <module>
    main()
  File "/usr/share/volatility/vol.py", line 174, in main
    command = cmds[module](config)
  File "/usr/share/volatility/contrib/plugins/autoruns.py", line 133, in __init__
    hivelist.HiveList.__init__(self, config, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/volatility/plugins/common.py", line 50, in __init__
    help = "Skip unallocated objects (e.g. 0xbad0b0b0)")
  File "/usr/lib/python2.7/dist-packages/volatility/conf.py", line 363, in add_option
    self.optparser.add_option("-{0}".format(short_option), "--{0}".format(option), **args)
  File "/usr/lib/python2.7/optparse.py", line 1020, in add_option
    self._check_conflict(option)
  File "/usr/lib/python2.7/optparse.py", line 995, in _check_conflict
    option)
optparse.OptionConflictError: option -W/--show-unallocated: conflicting option string(s): -W

**Comment by tomchop** [comment]
There seems to be conflicting options (in this case `-W`, inherited from the `HiveList` plugins) with some other plugin in your plugin folder. What happens if you run the plugin from its own directory?

**Comment by Arvandor** [comment]
Aha, that seemed to work. I'll have to keep that in mind with third party
plugins, that I can't just dump them all in the same folder.

It does throw this error, though
WARNING : volatility.obj      : NoneObject as string: Value data is
unreadable
but it still seems to work

**Comment by tomchop** [comment]
I think that's a common problem when trying to read keys that don't exist.
I'll have to try/catch my way around it.

On Tue, Mar 17, 2015 at 6:43 PM, Arvandor <notifications@github.com> wrote:

> Aha, that seemed to work. I'll have to keep that in mind with third party
> plugins, that I can't just dump them all in the same folder.
>
> It does throw this error, though
> WARNING : volatility.obj : NoneObject as string: Value data is
> unreadable
> but it still seems to work
>
> On Tue, Mar 17, 2015 at 9:06 AM, Thomas Chopitea <notifications@github.com
> >
> wrote:
>
> > There seems to be conflicting options (in this case -W, inherited from
> > the HiveList plugins) with some other plugin in your plugin folder. What
> > happens if you run the plugin from its own directory?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/tomchop/volatility-autoruns/issues/4#issuecomment-82397210
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomchop/volatility-autoruns/issues/4#issuecomment-82494693>
> .
>



-- 
Thomas Chopitea

**Comment by Arvandor** [comment]
Yes indeed!

Thank you for the prompt help! I've been meaning to write some kind of
script to take care of this very thing... it somehow hadn't even occurred
to me to make it a plugin, duh. Always happy not to reinvent the wheel
though, glad I found this!

**Comment by tomchop** [comment]
Glad it helped you!
