### ISSUE TITLE
Autoruns.py error

### ISSUE THREAD

**Issue by walkr113** [tomchop/volatility-autoruns#8]
I just downloaded autoruns.py and installed it in the contrib/plugins folder.  I specify the --plugins=/contrib/plugins option but I"m getting the error:  **\* Failed to import volatility.plugins.autoruns (SyntaxError: invalid syntax (autoruns.py, line 265))  What is wrong with the syntax of that line?  

```
    values = {str(name): str(dat) for name, dat in self.regapi.reg_yield_values(hive_name='system', key='', given_root=service_key)}
```

**Comment by tomchop** [comment]
What version of python are you running?

**Comment by walkr113** [comment]
2.6

**Comment by tomchop** [comment]
This can come from your python version. Have you tried with a python 2.7 interpreter?
